import utils from './utils.js';

const descriptions = [
  'With ten years of experience in [genitive] backpack [name] comes to our course to teach the art (as [gender] calls it) of programming in [language]. As [gender] believes that life is about giving and teaching is giving, [gender] will give you whatever you will need to be the best.',
  'Author of the best selling books about [language], [name] joined our board of teachers in order to spread [genitive] knowledge with our students. You will meet [dative] in our classes every Monday and Thursday.',
  'There is nothing better than [language]. Or so [name] says. Sometimes [gender] will allow [dative]self to walk through our virtual campus and read some sketchy literature, but rest assured: [gender] will connect with people just like [gender] connects with book characters.',
  'Sometimes life gives you lemons. And sometimes it gives you [language]. Sometimes it gives you lemons and [language] and [name]. And then is the time to start making some lemonade with [genitive] help. Prepare yourself for this course and prepare a good lemonade too!',
  'Three times winner of the best designer award, [name] changed [genitive] careere more than once ([genitive] political views too). When [gender] started programming [gender] had no idea of the vast universe that will open up in front of [dative]. Now [gender] is in love with programming and so will you!',
  'For the past 24 years [name] was the head of the [language] team for Google. While [gender] is not restricting [dative]self to [language], [gender] keeps at heart this programming language, so [gender] secretly wants everyone to learn it.',
];

async function populateUsers(speakers) {
  const container = utils.qs('.speakers-container');

  speakers.forEach((speaker) => {
    const language = ['JavaScript', 'PHP', 'C#', 'Python', 'Ruby', 'Kotlin'][
      Math.floor(Math.random() * 6)
    ];

    const article = utils.createElement({
      tagName: 'article',
    });

    article.appendChild(
      utils.createElement({
        tagName: 'img',
        src: speaker.picture,
        alt: `Image for ${speaker.name}`,
      })
    );

    const div = utils.createElement({
      class: 'speaker-info',
    });

    div.appendChild(
      utils.createElement({
        tagName: 'h3',
        class: 'name',
        textContent: speaker.name,
      })
    );
    div.appendChild(
      utils.createElement({
        tagName: 'h3',
        class: 'language',
        textContent: language,
      })
    );
    div.appendChild(
      utils.createElement({
        tagName: 'p',
        class: 'title',
        textContent: `Professor of ${language}`,
      })
    );
    article.appendChild(div);

    const index = Math.floor(Math.random() * descriptions.length);
    const desc = descriptions[index];

    descriptions.splice(index, 1);

    article.appendChild(
      utils.createElement({
        tagName: 'p',
        class: 'speaker-description',
        textContent: desc
          .replaceAll('[genitive]', speaker.gender === 'male' ? 'his' : 'her')
          .replaceAll('[dative]', speaker.gender === 'male' ? 'him' : 'her')
          .replaceAll('[gender]', speaker.gender === 'male' ? 'he' : 'she')
          .replaceAll('[name]', speaker.name)
          .replaceAll('[language]', language),
      })
    );

    container.appendChild(article);
  });

  const button = utils.qs('#teachers button');

  button.textContent = 'more';
  button.appendChild(
    utils.createElement({
      tagName: 'img',
      src: './img/burger/arrow_down.png',
      alt: 'More speakers',
    })
  );
}

// Instead of creating speakers I'll simply grab them randomly from randomuser.me
// Random persons will be generated by randomuser.me and I will store them inside an array.
// Sometimes the API experiences errors (usually 500 internal server error), so the opperation
// will be tried over and over again until a result is present.
export default async function grabRandomUser() {
  const results = [];

  async function getResults() {
    try {
      const request = await fetch('https://randomuser.me/api/?results=6');
      const user = await request.json();

      user.results.forEach((u) => {
        results.push({
          gender: u.gender,
          name: `${u.name.last} ${u.name.first}`,
          picture: u.picture.large,
        });
      });

      populateUsers(results);
    } catch (e) {
      getResults();
    }
  }

  getResults();
}
